name: Update README all day at 10:21

on:
  push:
  workflow_dispatch:
  schedule:
    # “At 10:21 every day.”
    - cron: '21 10 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Pierre Legoux
          author_email: votre-email@gmail.com
          force: false
          signoff: false
          message: ':memo: README.md updated by Gabot'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
